
services:
  neo4j:
    image: neo4j:2025
    restart: unless-stopped
    ports:
      # Neo4j Browser: http://localhost:7474
      #   Default username: neo4j
      #   Default password: neo4j (change on first login)
      - ${NEO4J_UI_PORT}:7474
      - ${NEO4J_BOLT_PORT}:7687
    environment:
      - 'NEO4J_AUTH=neo4j/${NEO4J_PASS}'
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASS}", "RETURN 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    # ports:
      # - ${POSTGRES_PORT}:5432
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PGADMIN_UI_PORT}:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}'

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    restart: unless-stopped
    ports:
    #   - 5671:5671
    #   - 5672:5672
    #   - 15671:15671
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis:
    image: redis:8.6-alpine
    restart: unless-stopped
    # ports:
      # - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s

volumes:
  rabbitmq_data:
  neo4j_data:
  postgres_data:

