
services:
  thumbnailer:
    image: giobyte8/thumbnailer:dev
    restart: unless-stopped
    environment:
      - 'LOG_LEVEL=INFO'

      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_PASS=${RABBITMQ_PASS}'
      - 'RABBITMQ_VHOST=/'

      - 'AMQP_EXCHANGE=GL_EXCHANGE'
      - 'AMQP_QUEUE_THUMB_GEN_REQUESTS=GL_GEN_THUMB_REQUESTS'
      - 'AMQP_QUEUE_THUMB_DEL_REQUESTS=GL_DEL_THUMB_REQUESTS'

      - 'THUMBNAIL_WIDTHS_PX=512,256'
      - 'DIR_ORIGINALS_ROOT=/media/originals'
      - 'DIR_THUMBNAILS_ROOT=/media/thumbs'

      - 'OTEL_ENABLED=true'
      - 'OTEL_COLLECTOR_GRPC_ENDPOINT=otelcol:4317'
    depends_on:
      - rabbitmq

  galleries:
    image: giobyte8/galleries:dev
    restart: unless-stopped
    ports:
      - ${GL_UI_PORT}:8100
      - ${GL_UI_SCHEDULER_PORT}:8101
    environment:
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_PORT=5672'
      - 'RABBITMQ_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_PASS=${RABBITMQ_PASS}'
      - 'RABBITMQ_VHOST=/'

      - 'NEO4J_HOST=neo4j'
      - 'NEO4J_PORT=7687'
      - 'NEO4J_USER=${NEO4J_USER}'
      - 'NEO4J_PASS=${NEO4J_PASS}'

      - 'GL_SCHEDULER_DB=/mnt/runtime/scheduler.db'
      - 'GL_CONTENTS_ROOT_PATH=/media/originals'

      - 'OTEL_ENABLED=true'
      - 'OTEL_COLLECTOR_GRPC_ENDPOINT=otelcol:4317'
      - 'OTEL_COLLECTOR_HTTP_ENDPOINT=http://otelcol:4318'
    depends_on:
      - rabbitmq
      - neo4j

  estatico:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "${GL_ESTATICO_PORT}:8888/tcp"
      - "${GL_ESTATICO_PORT}:8888/udp"
    volumes:
      - estatico_caddy_data:/data/caddy
      - estatico_caddy_config:/config
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${GL_PATH_ORIGINALS}:/data/media:ro
      - ${GL_PATH_THUMBS}:/data/thumbs:ro


volumes:
  estatico_caddy_data:
  estatico_caddy_config: